#!/bin/bash

ME=$(dirname $0)

NO_FILTER=0
if [ "$1" == "--no-filter" ];
then
        NO_FILTER=1
        shift
fi

if [ "$1" == "" -o "$2" != "" ];
then
	echo "expected: test [--no-filter] file.rkt"
        exit 1
fi

REQUIRE='(require (submod "'"$1"'" test))'
if [ "$NO_FILTER" == "0" ];
then
        racket -l errortrace -l racket/base -e "$REQUIRE"
else
        racket -l errortrace -l racket/base -e "$REQUIRE" 2>&1 | python3 $ME/reformat-logs.py
fi
