#!/bin/bash

ME=$(dirname $0)

NO_FILTER=0
if [ "$1" == "--no-filter" ];
then
        NO_FILTER=1
        shift
fi

if [ "$1" == "" -o "$2" != "" ];
then
	echo "expected: test [--no-filter] (file.rkt | --all)"
        exit 1
fi

if [ "$1" == "--all" ];
then
        NPROC=$(getconf _NPROCESSORS_ONLN 2> /dev/null || getconf NPROCESSORS_ONLN 2> /dev/null || 4) # number of CPU cores
        echo "running: raco test src -t -j $NPROC"
        raco test src -t -j $NPROC
else
        REQUIRE='(require (submod "'"$1"'" test))'
        if [ "$NO_FILTER" == "1" ];
        then
                racket -l errortrace -l racket/base -e "$REQUIRE"
        else
                racket -l errortrace -l racket/base -e "$REQUIRE" 2>&1 | python3 $ME/reformat-logs.py
        fi
fi