//! Fixed-point execution for judgments generated by [`judgment_fn!`](crate::judgment_fn).
//!
//! A generated judgment function packages its arguments into a unique input
//! type and supplies this module with four things:
//!
//! * a tracing-span constructor;
//! * a thread-local [`JudgmentCache`] dedicated to that judgment;
//! * the input value for this call; and
//! * an `execute_rules` closure that evaluates every applicable rule once and
//!   returns the values proven in that pass.
//!
//! [`execute_judgment`] turns those single-pass rule evaluations into a
//! recursive least-fixed-point computation.
//!
//! ## Active recursion and convergence
//!
//! Each fresh call pushes a [`StackEntry`] containing an initially empty output
//! approximation. If evaluating its rules recursively requests the same
//! judgment input, [`ExecutionStack::search`] returns that current approximation
//! instead of recursing forever and marks the entry as having dependents.
//!
//! After a rule pass, [`ExecutionStack::update`] merges the newly proven values
//! into the approximation. Judgment outputs must grow monotonically: a later
//! pass may add proven values but may not remove one. Another pass is needed
//! only when the value set grew *and* a recursive dependent observed an earlier
//! approximation. Otherwise the current output is final.
//!
//! Different proof trees for the same proven value do not affect convergence.
//! Proofs are metadata, and [`merge_proven_outputs`] retains the smallest proof
//! observed for each value.
//!
//! ## Completed-result memoization
//!
//! The active execution stack is separate from [`memo`]. The stack stores
//! incomplete approximations used to break recursive cycles; the memo layer
//! stores only completed positive results. Each call therefore checks, in order:
//!
//! 1. the active stack for a recursive cycle;
//! 2. completed results from a still-valid enclosing iteration.
//!
//! A call that misses both paths opens an active stack entry and a
//! [`memo::IterationGuard`]. If its approximation grows, completed descendant
//! memo entries from the obsolete pass are invalidated before rules execute
//! again. At convergence, the final output and valid descendants move into the
//! parent iteration. Completing the top-level judgment discards its table, so
//! no memoized result survives between independent calls. See the [`memo`]
//! module for that lifecycle in detail.
//!
//! ## Cleanup and failures
//!
//! [`ActiveJudgmentGuard`] removes active stack state during unwinding, while
//! [`memo::IterationGuard`] removes provisional memo state. This prevents a
//! panic in a rule body from making later calls appear recursive or memoized.
//!
//! This module returns only proven values and proof trees. The generated
//! judgment function separately accumulates failure diagnostics for a pass and
//! uses them if the final [`ProofMap`] is empty. Empty results are not memoized,
//! because the proof map does not contain enough information to reconstruct
//! those diagnostics.

use std::{cell::RefCell, fmt::Debug, hash::Hash, thread::LocalKey};

use crate::Map;

use super::{insert_smallest_proof, memo, ProofTree};

/// The current proven values and smallest known proof for each value.
type ProofMap<Output> = Map<Output, ProofTree>;

/// Per-judgment thread-local state generated by [`judgment_fn!`](crate::judgment_fn).
///
/// One cache exists for each generated judgment, so `Input` and `Output` are
/// concrete and do not require the type erasure used by the shared memo layer.
/// The `RefCell` permits nested calls on the same thread to inspect and update
/// active approximations dynamically.
///
/// This type is public only because exported macro expansions must be able to name it.
#[doc(hidden)]
pub struct JudgmentCache<Input, Output> {
    /// Active calls to this judgment, ordered by recursive call depth.
    active: RefCell<ExecutionStack<Input, ProofMap<Output>>>,
}

impl<Input, Output> Default for JudgmentCache<Input, Output> {
    /// Create a per-judgment cache with no active evaluations.
    fn default() -> Self {
        Self {
            active: RefCell::new(ExecutionStack::default()),
        }
    }
}

/// Execute one judgment's rules until its proven output values reach a fixed point.
///
/// `tracing_span` creates the span used for each rule pass. `cache` is the
/// thread-local active stack generated for this particular judgment. `input`
/// identifies the call, and `execute_rules` performs one complete rule pass for
/// that input.
///
/// Reentrant calls with the same input receive the approximation accumulated so
/// far. A fresh call returns only after its semantic output stops changing, and
/// the returned map contains the smallest proof observed for each proven value.
///
/// This function is public only because exported macro expansions must be able to call it.
#[doc(hidden)]
pub fn execute_judgment<Input, Output>(
    tracing_span: impl Fn(&Input) -> tracing::Span,
    cache: &'static LocalKey<JudgmentCache<Input, Output>>,
    input: Input,
    mut execute_rules: impl FnMut(Input) -> ProofMap<Output>,
) -> ProofMap<Output>
where
    Input: Clone + Eq + Debug + Hash + 'static,
    Output: Clone + Eq + Debug + Hash + Ord + 'static,
{
    // Recursive judgment chains can exceed the native stack even when they are
    // converging normally. Move this evaluation to a larger stack segment when
    // the remaining stack drops below `stacker`'s requested red zone.
    stacker::maybe_grow(32 * 1024, 1024 * 1024, || {
        // Recursive cycle: this exact judgment input is already being evaluated.
        // Return its current approximation to break the cycle. `search` also marks
        // the active entry as having a dependent, so newly proven values will make
        // the enclosing fixed-point loop run again.
        if let Some(output) = cache.with(|cache| cache.active.borrow_mut().search(&input)) {
            tracing::debug!("recursive call to {:?}, yielding {:?}", input, output);
            return output;
        }

        // Completed in this fixed-point iteration: a nested call already proved a
        // positive result for this input, and no enclosing approximation has grown
        // since then. Reuse it until an iteration invalidation clears the table.
        if let Some(output) = memo::lookup_iteration(&input) {
            tracing::debug!(
                "iteration-memoized call to {:?}, yielding {:?}",
                input,
                output
            );
            return output;
        }

        // Execute the rules to compute the value. If executing the rules required recursively
        // reading the result of the current rule, then execute until a fixed-point is reached.
        // Otherwise (no recursion) just compute a single iteration.
        //
        // The result will be cached in the memo-table for this iteration and then added into
        // the parent's table. Whenever this judgment (or a parent) must run a second iteration,
        // it clears the intermediate cached results since they may change because recursive
        // calls will yield a new value.
        cache.with(|cache| cache.active.borrow_mut().push(&input, Map::new()));
        let active_guard = ActiveJudgmentGuard::new(cache, &input);
        let iteration_guard = memo::IterationGuard::begin();
        loop {
            // The current judgment's provisional memo table is topmost here and
            // contains no completed descendants yet. `begin` creates it empty for
            // the first pass; `invalidate` clears it before every repeated pass.
            // The current judgment's own approximation lives in `active_guard`'s
            // execution-stack entry, not in this memo table.
            iteration_guard.assert_is_top_and_empty();

            // Run the user's judgment rules and then trace the output.
            let span = tracing_span(&input);
            let _guard = span.enter();
            let output = execute_rules(input.clone());
            tracing::debug!(?output);

            // Merge this round's proven values into the active approximation.
            // `update` requests another round only when the value set grew and
            // a recursive call consumed an earlier approximation. If no such
            // dependent exists, the newly computed result is already final.
            let repeat = cache.with(|cache| cache.active.borrow_mut().update(&input, output));
            if !repeat {
                break;
            }

            tracing::debug!("proven values changed, re-executing until a fixed point is reached");

            // Descendants completed in this round may have depended on the old
            // approximation. Clear them before evaluating the rules again so
            // they cannot be reused as though they were valid at the new point.
            iteration_guard.invalidate();
        }

        // Remove and return the final approximation, then transfer the positive
        // entries completed in its last valid iteration into the parent memo
        // scope. If this was the top-level judgment, completing its iteration
        // instead discards the table so no cache survives the call.
        let output = active_guard.pop();
        iteration_guard.complete(&input, &output);
        output
    })
}

/// Common bounds for values stored in a generated judgment's active stack.
///
/// This private trait is a readability alias; its blanket implementation adds
/// no behavior beyond the listed bounds.
trait RuntimeValue: Clone + Eq + Debug + Hash + 'static {}
impl<T: Clone + Eq + Debug + Hash + 'static> RuntimeValue for T {}

/// Owns cleanup of one active [`ExecutionStack`] entry.
///
/// A fresh evaluation pushes the entry before creating this guard. Normal
/// completion consumes the guard through [`ActiveJudgmentGuard::pop`] and
/// returns the final approximation. If rule evaluation unwinds first, `Drop`
/// removes the entry and discards its incomplete output.
struct ActiveJudgmentGuard<Input, Output>
where
    Input: RuntimeValue,
    Output: RuntimeValue + Ord,
{
    /// The generated judgment's thread-local active stack.
    cache: &'static LocalKey<JudgmentCache<Input, Output>>,

    /// The exact input used to verify that this guard pops the correct stack entry.
    input: Input,

    /// Whether `Drop` still owns cleanup because normal completion has not popped the entry.
    active: bool,
}

impl<Input, Output> ActiveJudgmentGuard<Input, Output>
where
    Input: RuntimeValue,
    Output: RuntimeValue + Ord,
{
    /// Begin guarding the active entry that the caller just pushed for `input`.
    fn new(cache: &'static LocalKey<JudgmentCache<Input, Output>>, input: &Input) -> Self {
        Self {
            cache,
            input: input.clone(),
            active: true,
        }
    }

    /// Pop this evaluation normally and return its final output approximation.
    ///
    /// Marking the guard inactive first prevents its subsequent `Drop` from
    /// trying to remove the same entry a second time.
    fn pop(mut self) -> ProofMap<Output> {
        self.active = false;
        self.cache
            .with(|cache| cache.active.borrow_mut().pop(&self.input))
    }
}

impl<Input, Output> Drop for ActiveJudgmentGuard<Input, Output>
where
    Input: RuntimeValue,
    Output: RuntimeValue + Ord,
{
    /// Remove and discard an incomplete active entry during unwinding.
    fn drop(&mut self) {
        if self.active {
            self.cache
                .with(|cache| cache.active.borrow_mut().pop(&self.input));
        }
    }
}

/// Active evaluations of one generated judgment on the current thread.
///
/// Entries are ordered from the oldest call to the currently executing call.
/// Different inputs may be active simultaneously through recursion, but a
/// repeated input is handled by [`ExecutionStack::search`] and is never pushed
/// twice. This makes the vector both a recursion-detection set and a call stack.
struct ExecutionStack<Input, Output> {
    /// Active calls and the approximations each recursive caller may observe.
    entries: Vec<StackEntry<Input, Output>>,
}

impl<Input, Output> Default for ExecutionStack<Input, Output> {
    /// Create an execution stack with no active judgment calls.
    fn default() -> Self {
        Self {
            entries: Vec::new(),
        }
    }
}

/// Runtime state for one active judgment input.
///
/// `output` is the monotonically growing approximation returned to recursive
/// calls. `has_dependents` records whether any such call has observed it; only
/// then can growth require another rule pass.
struct StackEntry<Input, Output> {
    /// The complete generated judgment input identifying this active call.
    input: Input,

    /// The current output approximation, initially empty for a fresh evaluation.
    output: Output,

    /// Whether a recursive call has consumed this entry's approximation.
    has_dependents: bool,
}

impl<Input, Output> ExecutionStack<Input, Output>
where
    Input: RuntimeValue,
    Output: RuntimeValue,
{
    /// Detect an active call with the same input and return its approximation.
    ///
    /// A match is a recursive dependency, so this also sets `has_dependents` on
    /// the owning entry. If that approximation later grows, its fixed-point loop
    /// must execute the rules again for the dependent to observe the new values.
    fn search(&mut self, input: &Input) -> Option<Output> {
        for entry in &mut self.entries {
            if entry.input == *input {
                entry.has_dependents = true;
                return Some(entry.output.clone());
            }
        }

        None
    }

    /// Push a fresh active input and its initial output approximation.
    ///
    /// The uniqueness assertion enforces that repeated inputs take the recursive
    /// `search` path instead of creating a second fixed-point computation.
    fn push(&mut self, input: &Input, output: Output) {
        assert!(
            self.entries.iter().all(|entry| entry.input != *input),
            "judgment is already active"
        );
        self.entries.push(StackEntry {
            input: input.clone(),
            output,
            has_dependents: false,
        });
    }

    /// Pop the most recent active call and return its approximation.
    ///
    /// Judgment evaluations are nested, so normal completion and unwinding must
    /// be last-in, first-out. The input assertion catches mismatched guards.
    fn pop(&mut self, input: &Input) -> Output {
        let top = self.entries.pop().expect("no active judgment to pop");
        assert_eq!(top.input, *input);
        top.output
    }

    /// Borrow the currently executing entry after verifying its input.
    ///
    /// Rule-pass results can update only the top entry for this judgment; any
    /// older entry is suspended beneath the current recursive call.
    fn top(&mut self, input: &Input) -> &mut StackEntry<Input, Output> {
        let top = self.entries.last_mut().expect("no active judgment");
        assert_eq!(top.input, *input);
        top
    }
}

impl<Input, Output> ExecutionStack<Input, ProofMap<Output>>
where
    Input: RuntimeValue,
    Output: RuntimeValue + Ord,
{
    /// Merge one rule pass into the active approximation and decide whether to repeat.
    ///
    /// Semantic growth matters only if a recursive dependent previously consumed
    /// the old approximation. Without a dependent, the complete rule pass has
    /// already computed the final output and no observer needs to be revisited.
    fn update(&mut self, input: &Input, output: ProofMap<Output>) -> bool {
        let top = self.top(input);
        merge_proven_outputs(&mut top.output, output) && top.has_dependents
    }
}

/// Merge a new judgment result into its current approximation.
///
/// Positive judgment outputs must grow monotonically, so every key in `current`
/// must also occur in `next`. Given that subset invariant, a length change means
/// that the pass proved at least one new value. Proof-only changes do not count
/// as semantic growth, but the smallest proof observed for each value is retained.
///
/// Returns `true` exactly when the set of proven values grew.
fn merge_proven_outputs<Output: Ord + Clone>(
    current: &mut ProofMap<Output>,
    mut next: ProofMap<Output>,
) -> bool {
    assert!(
        current.keys().all(|value| next.contains_key(value)),
        "judgment fixed-point output lost a previously proven value",
    );

    let values_changed = current.len() != next.len();
    for (value, proof) in std::mem::take(current) {
        insert_smallest_proof(&mut next, value, proof);
    }
    *current = next;
    values_changed
}

#[cfg(test)]
mod tests {
    use std::cell::Cell;

    use super::*;

    thread_local! {
        static CACHE: JudgmentCache<(), u32> = JudgmentCache::default();
        static ITERATIONS: Cell<usize> = const { Cell::new(0) };
    }

    fn growing_proof() -> ProofMap<u32> {
        execute_judgment(
            |_| tracing::Span::none(),
            &CACHE,
            (),
            |_| {
                let iteration = ITERATIONS.get() + 1;
                ITERATIONS.set(iteration);
                assert!(
                    iteration <= 8,
                    "proof metadata forced unbounded judgment iteration"
                );

                let previous = growing_proof();
                let proof = match previous.get(&0) {
                    Some(proof) => ProofTree::new("recursive", None, vec![proof.clone()]),
                    None => ProofTree::leaf("base"),
                };
                Map::from([(0, proof)])
            },
        )
    }

    fn large_proof() -> ProofTree {
        ProofTree::new("large", None, vec![ProofTree::leaf("child")])
    }

    #[test]
    fn proof_metadata_does_not_force_iteration_and_smallest_proof_wins() {
        ITERATIONS.set(0);

        let output = growing_proof();

        assert_eq!(ITERATIONS.get(), 2);
        assert_eq!(output[&0].total_nodes(), 1);
    }

    #[test]
    fn merge_reports_only_new_values_and_keeps_the_smallest_proof() {
        let small = ProofTree::leaf("small");
        let mut current = Map::from([(0, small.clone())]);

        assert!(!merge_proven_outputs(
            &mut current,
            Map::from([(0, large_proof())]),
        ));
        assert_eq!(current, Map::from([(0, small.clone())]));

        assert!(merge_proven_outputs(
            &mut current,
            Map::from([(0, large_proof()), (1, ProofTree::leaf("one"))]),
        ));
        assert_eq!(current.get(&0), Some(&small));
        assert!(current.contains_key(&1));
    }

    #[test]
    #[should_panic(expected = "lost a previously proven value")]
    fn merge_rejects_non_monotonic_outputs() {
        let mut current = Map::from([(0, ProofTree::leaf("zero"))]);

        merge_proven_outputs(&mut current, Map::new());
    }
}
